### ISSUE TITLE
RCurl

### ISSUE THREAD

**Issue by jeroen** [r-windows/checks#3]
The `Makevars.win` file for RCurl links to `-lrtmp` and `-lidn` on i386 which we no longer use. It should [remove those linker flags](https://github.com/r-windows/RCurl/commit/03be95ff8f910ac51d49e7010ffb1823de2ac638). Workaround:

```r
remotes::install_github("r-windows/RCurl")
```

**Comment by adamrobinson361** [comment]
Is there a backwards compatible solution for this that would allow Rcurl versions with links to those packages to build?

**Comment by adamrobinson361** [comment]
I work in an organisation where we currently are only able to develop in R using windows desktops and windows servers. We have countless packrat enabled projects from over the past year or so and struggle to restore/collaborate on our infrastructure due to packages such as RCurl, XML etc not being able to build due to missing system dependencies. I'm trying to set up a build agent using windows server and rtools that we can use to build and deliver all of our products; models, reports and apps.

**Comment by jeroen** [comment]
I think you are better off installing the CRAN binary packages rather than building them from source on Windows. Note that CRAN itself does not store older versions of binary packages, however you can get them from the MRAN time machine: https://mran.microsoft.com/timemachine

**Comment by jeroen** [comment]
I've added stubs to `mingw-w64-curl` for `libidn.a` and `librtmp.a`.
