### ISSUE TITLE
zlibbioc, Rhtslib, Rprotobuflib, Rhdf5lib

### ISSUE THREAD

**Issue by jeroen** [r-windows/checks#43]
These packages bundle Makefiles that do not respect BINPREF. 

On CRAN we installed the binaries from bioc for now.

**Comment by jeroen** [comment]
The dev version of Rhtslib seems much better: https://github.com/Bioconductor/Rhtslib

**Comment by jeroen** [comment]
Rprotobuflib seems to bundle a static lib that is not compatible with the new toolchain.

**Comment by grimbough** [comment]
Just tagging this post so I remember it exists.  I'm taking a look at whats required to fix Rhdf5lib soon, and this will probably lead to similar solutions for the other BioC packages that bundle precompiled libraries.  

Is there anyway to know which toolchain is being used during installation, like with `${R_ARCH}` for achitecture?  I thought about using the compiler version or something similar, but I don't know how reliable that would be.

**Comment by jeroen** [comment]
Yes! You can use the `R_COMPILED_BY` variable. For example have a look at the `Makevars.win` from:

  - magick: https://github.com/ropensci/magick/blob/master/src/Makevars.win
  - pdftools: https://github.com/ropensci/pdftools/blob/master/src/Makevars.win

These packages automatically download binaries from rwinlib, and I have put the static libs in the corresponding folder names:

  - imagemagick: https://github.com/rwinlib/imagemagick6
  - pdftools: https://github.com/rwinlib/poppler

**Comment by jeroen** [comment]
Please let me know if you need any help, because I have done this for 30 packages. All libraries should be in https://github.com/rwinlib.

Most static libraries will work for both the old and new toolchain. Only C++ libraries that use `std::string` are affected by the C++11 ABI change so those need separate builds to work with GCC 4.9.3 and GCC 8.

The convention that I use in rwinlib is that the `lib-4.9.3` directory contains the legacy binaries that only work with the old toolchain. The `lib` directory OTOH contains binaries that work for the new toolchain, and if there is no `lib-4.9.3` directory they also work for the old toolchain.

**Comment by grimbough** [comment]
Thanks for the information, Rwinlib looks like a great resource and I think something we (as in general Bioconductor developers) should look at more closely.  We're discussing it in our monthly teleconference tonight.

However, in the immediate term and looking only at the packages I maintain, I end up looking into this after getting this issue (https://github.com/grimbough/Rhdf5lib/issues/24) and the error message below made me think Rhdf5lib wouldn't install with the new toolchain:

> Error: package or namespace load failed for 'PLNmodels' in library.dynam(lib, package, package.lib):
DLL 'Rhdf5lib' not found: maybe not installed for this architecture?
Error: loading failed

However everything seems to work fine for me on a local version of R-testing, where I can compile and install from source on x86 and x64 and run all tests in a package (rhdf5) that depends on the library.  (This is not true for some of the other BioC packages listed in the issue title).

Is there something different about the CRAN build system that I'm not emulating, or is the absence of Rhdf5lib more philosophical because it isn't doing things the 'right' way?

Please feel free to point me to another issue if I'm deviating too much from the original topic here.

**Comment by jeroen** [comment]
I think you need to build `Rhdf5lib` windows binary package using `--merge-multiarch` or possibly `--force-biarch`  in order to get the dual build? 

The error message from R `DLL 'Rhdf5lib' not found` means that the package was built in single-arch mode, which is the default if the package has a `configure.win`.

**Comment by grimbough** [comment]
Thanks, I think there might be two issues here.  That error message comes from the CRAN logs e.g. https://www.r-project.org/nosvn/R.check/r-devel-windows-ix86+x86_64-gcc8/metacoder-00check.html so I guess the dual build isn't being used there?

I'm using `--force-biarch` locally and everything seems to work fine.  However I've just realised that I might not actually be using the new tool chain despite running R-testing:

```r
> R.version$status
[1] "Under development (Rtools 4.0)"
> system2("gcc", "--version")
gcc.exe (i686-posix-dwarf, Built by MinGW-W64 project) 4.9.3
```

That would explain why I have no issues, since that's the compiler I built the original binaries with.  I'll dig into the setup and try to understand what's taking priority here.

**Comment by jeroen** [comment]
I think it's fine, R does not take gcc  from the PATH, but using the `BINPREF` variable.

**Comment by jeroen** [comment]
> That error message comes from the CRAN logs e.g. https://www.r-project.org/nosvn/R.check/r-devel-windows-ix86+x86_64-gcc8/metacoder-00check.html so I guess the dual build isn't being used there?

Indeed, I have now asked CRAN to use the dual build.

The underlying problem is that usually BioConductor builds Rhdf5lib so they probably add the `--merge-multiarch`. However as we are now in the toolchain transition, CRAN is temporarily also building the Bioc packages.

**Comment by grimbough** [comment]
Awesome, the BioC build command is:

```
R.exe CMD INSTALL --merge-multiarch --build --library=Rhdf5lib.buildbin-libdir Rhdf5lib_1.8.0.tar.gz
```

That's a simpler fix than I was expecting!  I'll report back here after we've discussed some of the other packages, I know Rhtslib requires lots of system libraries and currently you have to mimic the structure of the BioC builder to compile locally, but I think Rwinlib could be really helpful in making it more portable.

Thanks for the all the help, you're more than welcome to join the teleconference today if you're interested.

**Comment by jeroen** [comment]
Is there a place where I can lookup the BioC build command for all bioc packages?

**Comment by grimbough** [comment]
There's a page with the build status of all packages at: 

http://bioconductor.org/checkResults/release/bioc-LATEST/index.html

You can then click on the 'OK' badge and you'll get more details for that particular build, including the command that was run e.g. 

http://bioconductor.org/checkResults/release/bioc-LATEST/a4/tokay1-buildsrc.html

There may be a few exceptions, but AFAIK everything is built with the same command, so just looking at one package should be sufficient to see how the build is executed.

**Comment by jeroen** [comment]
CRAN is now running GCC 8.3.0 on R 4.0 and up. Let me know if you need help with fixing packages
