### ISSUE TITLE
nandb

### ISSUE THREAD

**Issue by jeroen** [r-windows/checks#52]
Fails test in both architectures like so:

```
-- 1. Failure: number_timeseries works (@test-number.R#254)  -------------------
sort(lfnts) not equal to sort(ans0).
1/2 mismatches
x[2]: "50again_number_n_contiguous_timeseries_frames_per_set=20_swaps=auto=0_thr
x[2]: esh=Triangle=0.68_filt=NA.tif"
y[2]: "50again_number_n_contiguous_timeseries_frames_per_set=20_swaps=auto=5029_
y[2]: thresh=Triangle=0.68_filt=NA.tif"

== testthat results  ===========================================================
[ OK: 154 | SKIPPED: 0 | WARNINGS: 0 | FAILED: 1 ]
1. Failure: number_timeseries works (@test-number.R#254)

```

**Comment by jeroen** [comment]
Could be a problem in ijtiff again.

**Comment by rorynolan** [comment]
Hi @jeroen 
I'm surprised that updating libtiff would have this effect. That could mean that the values in the image read by different libtiffs are different, which seems super strange. I think it's an OS thing.
These results are different on different platforms because the routines used rely on C++'s `<random>`, which is implementation-specific and therefore the results are different on different platforms. These tests look a bit stupid but they've saved me from doing terrible things in the past.
I guess it could also be that the platform you're testing on has a different `<random>` implementation than anything I've tested on before (I've seen different results on AppVeyor and CRAN for this reason). Maybe I should be `skip_on_cran()` with this kind of stuff actually? 
What do you think?

**Comment by jeroen** [comment]
Yeah we're upgrading GCC so it might use a different random number generator. 

If you think it's not important, please submit a version to CRAN that skips this test. Because we cannot upgrade the toolchain if there are too many packages that fail tests.

**Comment by rorynolan** [comment]
Done.
Thanks for your work supporting libtiff in R.

**Comment by jeroen** [comment]
Fix is on CRAN. Thanks!
